"""added sms capability

Revision ID: 106f40bbb297
Revises: 1d107ef5a824
Create Date: 2018-04-03 11:27:08.323012

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '106f40bbb297'
down_revision = '1d107ef5a824'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allow_sms', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'allow_sms')
    # ### end Alembic commands ###
