"""Stupidly made first and last name unique

Revision ID: 1d107ef5a824
Revises: 35d30d9c45b4
Create Date: 2018-03-28 20:51:45.756643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d107ef5a824'
down_revision = '35d30d9c45b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_first_name', table_name='users')
    op.create_index(op.f('ix_users_first_name'), 'users', ['first_name'], unique=False)
    op.drop_index('ix_users_last_name', table_name='users')
    op.create_index(op.f('ix_users_last_name'), 'users', ['last_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_last_name'), table_name='users')
    op.create_index('ix_users_last_name', 'users', ['last_name'], unique=True)
    op.drop_index(op.f('ix_users_first_name'), table_name='users')
    op.create_index('ix_users_first_name', 'users', ['first_name'], unique=True)
    # ### end Alembic commands ###
