"""empty message

Revision ID: 84662a9bfec4
Revises: cdcd434c153f
Create Date: 2018-03-20 18:35:18.524523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84662a9bfec4'
down_revision = 'cdcd434c153f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twilio_account_sid', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('twilio_auth_token', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('twilio_number', sa.String(length=32), nullable=True))
    op.drop_column('users', 'twilio_account_sid_hash')
    op.drop_column('users', 'twilio_auth_token_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('twilio_auth_token_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('twilio_account_sid_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'twilio_number')
    op.drop_column('users', 'twilio_auth_token')
    op.drop_column('users', 'twilio_account_sid')
    # ### end Alembic commands ###
