"""added sync map id

Revision ID: ba4d9c065ff7
Revises: 84662a9bfec4
Create Date: 2018-03-24 18:58:59.086463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4d9c065ff7'
down_revision = '84662a9bfec4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sync_map_id', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sync_map_id')
    # ### end Alembic commands ###
