"""added location and duration to conferences

Revision ID: c78ee467fd35
Revises: 106f40bbb297
Create Date: 2018-04-04 12:24:32.784043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c78ee467fd35'
down_revision = '106f40bbb297'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conferences', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('conferences', sa.Column('region', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conferences', 'region')
    op.drop_column('conferences', 'duration')
    # ### end Alembic commands ###
