"""added authy components

Revision ID: cdcd434c153f
Revises: 67f4ad45e9b5
Create Date: 2018-02-27 15:30:30.526268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdcd434c153f'
down_revision = '67f4ad45e9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authy_user_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number_confirmed')
    op.drop_column('users', 'authy_user_id')
    # ### end Alembic commands ###
