"""added user contact details

Revision ID: d4ecdcba96fe
Revises: 5baa5fa8661a
Create Date: 2018-02-26 09:38:38.062263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ecdcba96fe'
down_revision = '5baa5fa8661a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=32), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone'])
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
