"""Added password and twilio account hashes

Revision ID: e13e6f7b6ddf
Revises: d4ecdcba96fe
Create Date: 2018-02-26 16:58:44.523436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e13e6f7b6ddf'
down_revision = 'd4ecdcba96fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('twilio_account_sid_hash', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('twilio_auth_token_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'twilio_auth_token_hash')
    op.drop_column('users', 'twilio_account_sid_hash')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
